* switch from custom su-me to generic su-to-root, adapt dependencies and   menu files accordingly. * move desktop file into standard XDG hierarchy.

diff --git a/src/sh/appinstaller b/src/sh/appinstaller
--- a/src/sh/appinstaller
+++ b/src/sh/appinstaller
@@ -1,12 +1,16 @@
 #!/bin/sh
 # appinstaller
 # (C) 2007 Fabian Wuertz <xadras@sidux.com>
-# (C) 2007 Stefan Lippers-Hollmann <s.l-h@gmx.de>
+# (C) 2007-2008 Stefan Lippers-Hollmann <s.l-h@gmx.de>
 # License: GPL
 
 [ -z "${1}" ] && exit 0
 
-[ "$(id -u)" -ne 0 ] && DISPLAY="" exec su-me "$0" "$@"
+if [ "$(id -u)" -ne 0 ]; then
+	[ -x "$(which su-to-root)" ] && exec su-to-root -c "${0} $@"
+	printf "ERROR: $0 needs root capabilities, please start it as root.\n\n" >&2
+	exit 1
+fi
 
 apt-get update
 apt-get install $1
